services:
  app:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/Smolathon?schema=public
      - JWT_ACCESS_SECRET=4fzovf0s6d1SIPii718YRwFkb0GhhV0SWdJOMpJiBN2UcpfsQX7wgAStCsoXyOCUEZuaVJd0x8di4JqjlgSBUzg2aFitGqxrqejMYYxOj1olfmqSU3Y4BbhLSZbIqbcKlNdJCqFwiEnXCn7oGtkWj9hitYretqvenvcAxpBm5PVYxwbsYcYyzGSZggSAWLsOkBWAsW1oSNXkPVuvxVTv8QQQhNhLaheWlGzhKSK90MuYLfWKBwmVrt3bCVXeMGky
      - JWT_REFRESH_SECRET=4ZVVxbMFkSdKXNCLaLuwdl0RDXVzETjnwfBDC3q4FefPa8cQdLULBfNy1N00TSEURTZTJOwPeng0lnDlCsvoLnakL9ZkOVNT3tpYoaat7GP9DiE2DcmMuw6bi1pcavJGfCrMS8Ug4wwS5GnMsQPSW6Z6l8TroFXI8szJTXDEQhDWDVa8bV07zEkpBYcu7X2a8Ls34CLsJblmGMLHKf7tAeq7Ve1sEUsOJjc1oLaYmy2VpPy2UuM8N7WOvnTSjlgk
      - JWT_ACCESS_EXPIRES_IN=2h
      - JWT_REFRESH_EXPIRES_IN=7d
      - TELEGRAM_BOT_TOKEN=7363774495:AAEoYDVNJ4UOIM41zucutYut26ImyozW6_g
      - TELEGRAM_CHAT_ID=-4836587006
      - BASE_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "sleep 5 && npx prisma db push --accept-data-loss && nest start --watch"

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Smolathon
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dumps/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  postgres_data:
